name: patrol_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  patrol: ^3.1.0

flutter:
  uses-material-design: true

patrol:
  app_name: My App
  android:
    package_name: com.example.patrol_test
